# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:35:19+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyQuery, BaseSecurity
from fastapi import Path

from models import (
    BatchInputSubscriptionBatchUpdateRequest,
    BatchResponseSubscriptionResponse,
    BatchResponseSubscriptionResponseWithErrors,
    Error,
    SettingsChangeRequest,
    SettingsResponse,
    SubscriptionCreateRequest,
    SubscriptionListResponse,
    SubscriptionPatchRequest,
    SubscriptionResponse,
)

app = MCPProxy(
    description='Provides a way for apps to subscribe to certain change events in HubSpot. Once configured, apps will receive event payloads containing details about the changes at a specified target URL. There can only be one target URL for receiving event notifications per app.',
    title='Webhooks API',
    version='v3',
    servers=[{'url': 'https://api.hubapi.com/'}],
)


@app.delete(
    '/webhooks/v3/{appId}/settings',
    tags=['webhook_configuration', 'webhook_subscription_handling'],
    security=[
        APIKeyQuery(name="hapikey"),
    ],
)
def delete__webhooks_v3__app_id__settings_clear(app_id: int = Path(..., alias='appId')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/webhooks/v3/{appId}/settings',
    tags=['webhook_configuration', 'webhook_subscription_handling'],
    security=[
        APIKeyQuery(name="hapikey"),
    ],
)
def get__webhooks_v3__app_id__settings_get_all(app_id: int = Path(..., alias='appId')):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/webhooks/v3/{appId}/settings',
    tags=['webhook_configuration'],
    security=[
        APIKeyQuery(name="hapikey"),
    ],
)
def put__webhooks_v3__app_id__settings_configure(
    app_id: int = Path(..., alias='appId'), body: SettingsChangeRequest = ...
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/webhooks/v3/{appId}/subscriptions',
    tags=['webhook_configuration', 'webhook_subscription_handling'],
    security=[
        APIKeyQuery(name="hapikey"),
    ],
)
def get__webhooks_v3__app_id__subscriptions_get_all(
    app_id: int = Path(..., alias='appId')
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/webhooks/v3/{appId}/subscriptions',
    tags=['webhook_subscription_handling'],
    security=[
        APIKeyQuery(name="hapikey"),
    ],
)
def post__webhooks_v3__app_id__subscriptions_create(
    app_id: int = Path(..., alias='appId'), body: SubscriptionCreateRequest = ...
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/webhooks/v3/{appId}/subscriptions/batch/update',
    tags=['webhook_subscription_handling'],
    security=[
        APIKeyQuery(name="hapikey"),
    ],
)
def update_subscription_batch_for_app(
    app_id: int = Path(..., alias='appId'),
    body: BatchInputSubscriptionBatchUpdateRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/webhooks/v3/{appId}/subscriptions/{subscriptionId}',
    tags=['webhook_subscription_handling'],
    security=[
        APIKeyQuery(name="hapikey"),
    ],
)
def archive_subscription_webhook(
    subscription_id: int = Path(..., alias='subscriptionId'),
    app_id: int = Path(..., alias='appId'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/webhooks/v3/{appId}/subscriptions/{subscriptionId}',
    tags=['webhook_subscription_handling'],
    security=[
        APIKeyQuery(name="hapikey"),
    ],
)
def get_subscription_by_id(
    subscription_id: int = Path(..., alias='subscriptionId'),
    app_id: int = Path(..., alias='appId'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch(
    '/webhooks/v3/{appId}/subscriptions/{subscriptionId}',
    tags=['webhook_subscription_handling'],
    security=[
        APIKeyQuery(name="hapikey"),
    ],
)
def update_subscription_patch_v3(
    subscription_id: int = Path(..., alias='subscriptionId'),
    app_id: int = Path(..., alias='appId'),
    body: SubscriptionPatchRequest = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
