# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:35:19+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import UUID

from pydantic import BaseModel, Field


class Status(Enum):
    PENDING = 'PENDING'
    PROCESSING = 'PROCESSING'
    CANCELED = 'CANCELED'
    COMPLETE = 'COMPLETE'


class HttpStatus(Enum):
    CONTINUE = 'CONTINUE'
    SWITCHING_PROTOCOLS = 'SWITCHING_PROTOCOLS'
    PROCESSING = 'PROCESSING'
    OK = 'OK'
    CREATED = 'CREATED'
    ACCEPTED = 'ACCEPTED'
    NON_AUTHORITATIVE_INFORMATION = 'NON_AUTHORITATIVE_INFORMATION'
    NO_CONTENT = 'NO_CONTENT'
    RESET_CONTENT = 'RESET_CONTENT'
    PARTIAL_CONTENT = 'PARTIAL_CONTENT'
    MULTI_STATUS = 'MULTI_STATUS'
    ALREADY_REPORTED = 'ALREADY_REPORTED'
    IM_USED = 'IM_USED'
    MULTIPLE_CHOICES = 'MULTIPLE_CHOICES'
    MOVED_PERMANENTLY = 'MOVED_PERMANENTLY'
    FOUND = 'FOUND'
    SEE_OTHER = 'SEE_OTHER'
    NOT_MODIFIED = 'NOT_MODIFIED'
    USE_PROXY = 'USE_PROXY'
    TEMPORARY_REDIRECT = 'TEMPORARY_REDIRECT'
    PERMANENT_REDIRECT = 'PERMANENT_REDIRECT'
    BAD_REQUEST = 'BAD_REQUEST'
    UNAUTHORIZED = 'UNAUTHORIZED'
    PAYMENT_REQUIRED = 'PAYMENT_REQUIRED'
    FORBIDDEN = 'FORBIDDEN'
    NOT_FOUND = 'NOT_FOUND'
    METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED'
    NOT_ACCEPTABLE = 'NOT_ACCEPTABLE'
    PROXY_AUTHENTICATION_REQUIRED = 'PROXY_AUTHENTICATION_REQUIRED'
    REQUEST_TIMEOUT = 'REQUEST_TIMEOUT'
    CONFLICT = 'CONFLICT'
    GONE = 'GONE'
    LENGTH_REQUIRED = 'LENGTH_REQUIRED'
    PRECONDITION_FAILED = 'PRECONDITION_FAILED'
    REQUEST_ENTITY_TOO_LARGE = 'REQUEST_ENTITY_TOO_LARGE'
    REQUEST_URI_TOO_LONG = 'REQUEST_URI_TOO_LONG'
    UNSUPPORTED_MEDIA_TYPE = 'UNSUPPORTED_MEDIA_TYPE'
    REQUESTED_RANGE_NOT_SATISFIABLE = 'REQUESTED_RANGE_NOT_SATISFIABLE'
    EXPECTATION_FAILED = 'EXPECTATION_FAILED'
    IM_A_TEAPOT = 'IM_A_TEAPOT'
    MISDIRECTED_REQUEST = 'MISDIRECTED_REQUEST'
    UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY'
    LOCKED = 'LOCKED'
    FAILED_DEPENDENCY = 'FAILED_DEPENDENCY'
    UPGRADE_REQUIRED = 'UPGRADE_REQUIRED'
    PRECONDITION_REQUIRED = 'PRECONDITION_REQUIRED'
    TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS'
    REQUEST_HEADERS_FIELDS_TOO_LARGE = 'REQUEST_HEADERS_FIELDS_TOO_LARGE'
    INTERNAL_STALE_SERVICE_DISCOVERY = 'INTERNAL_STALE_SERVICE_DISCOVERY'
    UNAVAILABLE_FOR_LEGAL_REASONS = 'UNAVAILABLE_FOR_LEGAL_REASONS'
    MIGRATION_IN_PROGRESS = 'MIGRATION_IN_PROGRESS'
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'
    NOT_IMPLEMENTED = 'NOT_IMPLEMENTED'
    BAD_GATEWAY = 'BAD_GATEWAY'
    SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE'
    GATEWAY_TIMEOUT = 'GATEWAY_TIMEOUT'
    HTTP_VERSION_NOT_SUPPORTED = 'HTTP_VERSION_NOT_SUPPORTED'
    VARIANT_ALSO_NEGOTIATES = 'VARIANT_ALSO_NEGOTIATES'
    INSUFFICIENT_STORAGE = 'INSUFFICIENT_STORAGE'
    LOOP_DETECTED = 'LOOP_DETECTED'
    NOT_EXTENDED = 'NOT_EXTENDED'
    NETWORK_AUTHENTICATION_REQUIRED = 'NETWORK_AUTHENTICATION_REQUIRED'


class ErrorCategory(BaseModel):
    httpStatus: HttpStatus
    name: str


class ErrorDetail(BaseModel):
    code: Optional[str] = Field(
        None, description='The status code associated with the error detail'
    )
    context: Optional[Dict[str, List[str]]] = Field(
        None,
        description='Context about the error condition',
        examples=[{'missingScopes': ['scope1', 'scope2']}],
    )
    in_: Optional[str] = Field(
        None,
        alias='in',
        description='The name of the field or parameter in which the error was found.',
    )
    message: str = Field(
        ...,
        description='A human readable message describing the error along with remediation steps where appropriate',
    )
    subCategory: Optional[str] = Field(
        None,
        description='A specific category that contains more specific detail about the error',
    )


class StandardError(BaseModel):
    category: ErrorCategory
    context: Dict[str, List[str]]
    errors: List[ErrorDetail]
    id: Optional[str] = None
    links: Dict[str, str]
    message: str
    status: str
    subCategory: Optional[Dict[str, Any]] = None


class SubscriptionBatchUpdateRequest(BaseModel):
    active: bool
    id: int


class EventType(Enum):
    contact_propertyChange = 'contact.propertyChange'
    company_propertyChange = 'company.propertyChange'
    deal_propertyChange = 'deal.propertyChange'
    ticket_propertyChange = 'ticket.propertyChange'
    product_propertyChange = 'product.propertyChange'
    line_item_propertyChange = 'line_item.propertyChange'
    contact_creation = 'contact.creation'
    contact_deletion = 'contact.deletion'
    contact_privacyDeletion = 'contact.privacyDeletion'
    company_creation = 'company.creation'
    company_deletion = 'company.deletion'
    deal_creation = 'deal.creation'
    deal_deletion = 'deal.deletion'
    ticket_creation = 'ticket.creation'
    ticket_deletion = 'ticket.deletion'
    product_creation = 'product.creation'
    product_deletion = 'product.deletion'
    line_item_creation = 'line_item.creation'
    line_item_deletion = 'line_item.deletion'
    conversation_creation = 'conversation.creation'
    conversation_deletion = 'conversation.deletion'
    conversation_newMessage = 'conversation.newMessage'
    conversation_privacyDeletion = 'conversation.privacyDeletion'
    conversation_propertyChange = 'conversation.propertyChange'


class SubscriptionCreateRequest(BaseModel):
    active: Optional[bool] = Field(
        None,
        description='Determines if the subscription is active or paused. Defaults to false.',
    )
    eventType: EventType = Field(
        ...,
        description='Type of event to listen for. Can be one of `create`, `delete`, `deletedForPrivacy`, or `propertyChange`.',
    )
    propertyName: Optional[str] = Field(
        None,
        description='The internal name of the property to monitor for changes. Only applies when `eventType` is `propertyChange`.',
    )


class SubscriptionPatchRequest(BaseModel):
    active: Optional[bool] = Field(
        None, description='Determines if the subscription is active or paused.'
    )


class SubscriptionResponse(BaseModel):
    active: bool = Field(
        ..., description='Determines if the subscription is active or paused.'
    )
    createdAt: datetime = Field(
        ...,
        description='When this subscription was created. Formatted as milliseconds from the [Unix epoch](#).',
    )
    eventType: EventType = Field(
        ...,
        description='Type of event to listen for. Can be one of `create`, `delete`, `deletedForPrivacy`, or `propertyChange`.',
    )
    id: str = Field(..., description='The unique ID of the subscription.')
    propertyName: Optional[str] = Field(
        None,
        description='The internal name of the property being monitored for changes. Only applies when `eventType` is `propertyChange`.',
    )
    updatedAt: Optional[datetime] = Field(
        None,
        description='When this subscription was last updated. Formatted as milliseconds from the [Unix epoch](#).',
    )


class Period(Enum):
    SECONDLY = 'SECONDLY'
    ROLLING_MINUTE = 'ROLLING_MINUTE'


class ThrottlingSettings(BaseModel):
    maxConcurrentRequests: int = Field(
        ...,
        description='The maximum number of HTTP requests HubSpot will attempt to make to your app in a given time frame determined by `period`.',
    )
    period: Period = Field(
        ...,
        description='Time scale for this setting. Can be either `SECONDLY` (per second) or `ROLLING_MINUTE` (per minute).',
    )


class BatchInputSubscriptionBatchUpdateRequest(BaseModel):
    inputs: List[SubscriptionBatchUpdateRequest]


class BatchResponseSubscriptionResponse(BaseModel):
    completedAt: datetime
    links: Optional[Dict[str, str]] = None
    requestedAt: Optional[datetime] = None
    results: List[SubscriptionResponse]
    startedAt: datetime
    status: Status


class BatchResponseSubscriptionResponseWithErrors(BaseModel):
    completedAt: datetime
    errors: Optional[List[StandardError]] = None
    links: Optional[Dict[str, str]] = None
    numErrors: Optional[int] = None
    requestedAt: Optional[datetime] = None
    results: List[SubscriptionResponse]
    startedAt: datetime
    status: Status


class Error(BaseModel):
    category: str = Field(..., description='The error category')
    context: Optional[Dict[str, List[str]]] = Field(
        None,
        description='Context about the error condition',
        examples=[
            {
                'invalidPropertyName': ['propertyValue'],
                'missingScopes': ['scope1', 'scope2'],
            }
        ],
    )
    correlationId: UUID = Field(
        ...,
        description='A unique identifier for the request. Include this value with any error reports or support tickets',
        examples=['aeb5f871-7f07-4993-9211-075dc63e7cbf'],
    )
    errors: Optional[List[ErrorDetail]] = Field(
        None, description='further information about the error'
    )
    links: Optional[Dict[str, str]] = Field(
        None,
        description='A map of link names to associated URIs containing documentation about the error or recommended remediation steps',
    )
    message: str = Field(
        ...,
        description='A human readable message describing the error along with remediation steps where appropriate',
        examples=['An error occurred'],
    )
    subCategory: Optional[str] = Field(
        None,
        description='A specific category that contains more specific detail about the error',
    )


class SettingsChangeRequest(BaseModel):
    targetUrl: str = Field(
        ...,
        description='A publicly available URL for Hubspot to call where event payloads will be delivered. See [link-so-some-doc](#) for details about the format of these event payloads.',
    )
    throttling: ThrottlingSettings


class SettingsResponse(BaseModel):
    createdAt: datetime = Field(
        ...,
        description='When this subscription was created. Formatted as milliseconds from the [Unix epoch](#).',
    )
    targetUrl: str = Field(
        ...,
        description='A publicly available URL for Hubspot to call where event payloads will be delivered. See [link-so-some-doc](#) for details about the format of these event payloads.',
    )
    throttling: ThrottlingSettings
    updatedAt: Optional[datetime] = Field(
        None,
        description='When this subscription was last updated. Formatted as milliseconds from the [Unix epoch](#).',
    )


class SubscriptionListResponse(BaseModel):
    results: List[SubscriptionResponse] = Field(
        ..., description='List of event subscriptions for your app'
    )
